# Marvel vs. DC - IMDB & Rotten Tomatoes Data Cleaner

Import tools needed

In [1]:
import os
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
from bs4 import BeautifulSoup
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd

Import CSV

In [2]:
csvfile = "marveldc.csv"
marvel_data = pd.read_csv(csvfile, encoding='utf-8')
marvel_data.head()

,Title,Year,Genre,Runtime,MPA_Rating,IMDB_Rating,IMDB_Votes,IMDB_Gross,Director,Stars,Description,Crit_Consensus,Tomato_Meter,Tomato_Review,Tom_Aud_Score,Tom_Ratings,Entity,ID
0,Captain America,1944,"Action, Adventure, Sci-Fi",244,Approved,5.5,844,0,Elmer Clifton,"Elmer Clifton,Dick Purcell,Lorna Gray,Lionel A...",Superhero Captain America battles the evil for...,"Find one of these old serials, friend. They're...",0,1,82,250,MARVEL,1
1,Howard the Duck,1986,"Action, Adventure, Comedy",110,PG,4.7,44073,16300000,Willard Huyck,"Willard Huyck,Lea Thompson,Jeffrey Jones,Tim R...",A sarcastic humanoid duck is pulled from his h...,"While it has its moments, Howard the Duck suff...",13,78,38,50000,MARVEL,2
2,Blade,1998,"Action, Horror, Sci-Fi",120,R,7.1,251243,70090000,Stephen Norrington,"Stephen Norrington,Wesley Snipes,Stephen Dorff...","A half-vampire, half-mortal man becomes a prot...","Though some may find the plot a bit lacking, B...",55,103,78,250000,MARVEL,3
3,X-Men,2000,"Action, Adventure, Sci-Fi",104,PG-13,7.4,580354,157300000,Bryan Singer,"Bryan Singer,Patrick Stewart,Hugh Jackman,Ian ...",In a world where mutants (evolved super-powere...,"Faithful to the comics and filled with action,...",82,174,83,250000,MARVEL,4
4,Blade II,2002,"Action, Fantasy, Horror",117,R,6.7,203813,82350000,Guillermo del Toro,"Guillermo del Toro,Wesley Snipes,Kris Kristoff...",Blade forms an uneasy alliance with the vampir...,Though Blade II offers more of what worked in ...,57,150,68,250000,MARVEL,5

Isolate Marvel Movies

In [13]:
marvel_only = marvel_data.loc[marvel_data['Entity'] == 'MARVEL', :]
marvel_only.head()

,Title,Year,Genre,Runtime,MPA_Rating,IMDB_Rating,IMDB_Votes,IMDB_Gross,Director,Stars,Description,Crit_Consensus,Tomato_Meter,Tomato_Review,Tom_Aud_Score,Tom_Ratings,Entity,ID
0,Captain America,1944,"Action, Adventure, Sci-Fi",244,Approved,5.5,844,0,Elmer Clifton,"Elmer Clifton,Dick Purcell,Lorna Gray,Lionel A...",Superhero Captain America battles the evil for...,"Find one of these old serials, friend. They're...",0,1,82,250,MARVEL,1
1,Howard the Duck,1986,"Action, Adventure, Comedy",110,PG,4.7,44073,16300000,Willard Huyck,"Willard Huyck,Lea Thompson,Jeffrey Jones,Tim R...",A sarcastic humanoid duck is pulled from his h...,"While it has its moments, Howard the Duck suff...",13,78,38,50000,MARVEL,2
2,Blade,1998,"Action, Horror, Sci-Fi",120,R,7.1,251243,70090000,Stephen Norrington,"Stephen Norrington,Wesley Snipes,Stephen Dorff...","A half-vampire, half-mortal man becomes a prot...","Though some may find the plot a bit lacking, B...",55,103,78,250000,MARVEL,3
3,X-Men,2000,"Action, Adventure, Sci-Fi",104,PG-13,7.4,580354,157300000,Bryan Singer,"Bryan Singer,Patrick Stewart,Hugh Jackman,Ian ...",In a world where mutants (evolved super-powere...,"Faithful to the comics and filled with action,...",82,174,83,250000,MARVEL,4
4,Blade II,2002,"Action, Fantasy, Horror",117,R,6.7,203813,82350000,Guillermo del Toro,"Guillermo del Toro,Wesley Snipes,Kris Kristoff...",Blade forms an uneasy alliance with the vampir...,Though Blade II offers more of what worked in ...,57,150,68,250000,MARVEL,5

Isolate Desired Columns

In [12]:
marvel_csv = marvel_only[['Title', 'Year', 'Runtime', 'Director','IMDB_Rating', 'IMDB_Votes', 'IMDB_Gross', 'Tomato_Meter', 'Tom_Aud_Score']]
marvel_csv.head()

,Title,Year,Runtime,Director,IMDB_Rating,IMDB_Votes,IMDB_Gross,Tomato_Meter,Tom_Aud_Score
0,Captain America,1944,244,Elmer Clifton,5.5,844,0,0,82
1,Howard the Duck,1986,110,Willard Huyck,4.7,44073,16300000,13,38
2,Blade,1998,120,Stephen Norrington,7.1,251243,70090000,55,78
3,X-Men,2000,104,Bryan Singer,7.4,580354,157300000,82,83
4,Blade II,2002,117,Guillermo del Toro,6.7,203813,82350000,57,68

Export to CSV

In [14]:
marvel_csv.to_csv("tableau_marvel.csv", index=False, header=True)